# Generated by Django 3.2.7 on 2021-10-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='npk',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
